### DISCUSSION TITLE
我按照教程把_data/friend/about放到根目录下的 source 文件夹但是出現錯誤

### DISCUSSION THREAD

**Discussion by snowball3605** [D-Sketon/hexo-theme-reimu#86] [Q&A] [answered]
錯誤:
Cannot GET /en/archives

連結是: http://xxx:xxx/en/about
但是我改為http://xxx:xxx/about
就能正常顯示
\\
\\
\\
mistake:
I followed the tutorial and put _data/friend/about into the source folder in the root directory, but an error occurred
Cannot GET /en/archives

The link is: http://xxx:xxx/en/about
But I changed to http://xxx:xxx/about
It will display normally

**Comment by qsy1225** [comment, marked as answer]
source文件夹新建一个en文件夹，将about放进去。应该就解决了。

**Reply by snowball3605** [reply]
謝謝我修好了，我居然沒有想到這個方法

**Reply by snowball3605** [reply]
那主頁呢
我點Home時，它會導向到http://xx:xx/en/
正常是http://xx:xx/

**Reply by qsy1225** [reply]
我没理解你的意思。这是我的网站，你可以去看一下。
https://qsy.wiki
对于我的网站，预设语言（简中）界面导向单纯的index.html
右上角语言改为英文或日文，网址会加个en、ja前缀。上方的Home、About等也会变为对应语言。

**Reply by snowball3605** [reply]
這是我的網站http://node.xhost.tw:30018

你點上面的４個按照會導向到http://node.xhost.tw:30018/en/archives

你手動改為http://node.xhost.tw:30018/archives

**Reply by qsy1225** [reply]
config.yml，裏面的lang.en改爲lang.zh-TW，
在config.yml文件加代碼：
```
i18n:
  enable: true # false | true
  type: [page, post]
  generator: [archive, category, tag, index]
  languages: [zh-TW, en] # 语言列表，第一个为默认语言
```
以上解決方案。我不知道你的建站方式，如果沒解決可以説説。

**Reply by qsy1225** [reply]
上面的代碼你的config.yml或config.reimu.yml應該有，就把languages改一改。

**Reply by snowball3605** [reply]
我現在改好了，確實不行

**Reply by qsy1225** [reply]
確保自己是正確地安裝主題。
你的網站的部分結構可能是
>-  _config.yml(外面的)
>-  themes
>> - reimu
>>> languages(裏面有四個yml文件)
>>>  source
>>> _config.yml（裏面的）
> - source
>>  _data
>> about
>> friends
>>en
>>>about
>>>friends

以上是一種。如果是的話，先看看外面的_config.yml，確保其lang: zh-TW。
裏面的_config.yml添加代碼：
```
i18n:
  enable: true
  type: [page, post]
  generator: [archive, category, tag, index]
  languages: [zh-TW, en] 
```
如果不是這種結構請告訴我
