### ISSUE TITLE
pc端文章末上下章节及评论消失的问题

### ISSUE THREAD

**Issue by virtualguard101** [D-Sketon/hexo-theme-reimu#102]
### 问题描述

[出现问题的文章](https://blog.virtualguard101.xyz/2025/04/26/web-build/)，问题为在pc端访问文章，出现文章末尾的“上一篇、下一篇”卡片及评论消失的情况。其余界面暂无问题，移动端上述功能正常

### 复现步骤

1. 按照文档进行评论区功能配置
2. 访问发现上述问题
3. 将除问题文章的其他任意文章进行置顶测试，发现问题仅在上述页面发生

### 你的 Hexo 和 插件版本

```text
Legend: production dependency, optional only, dev only

hexo-site@0.0.0 /home/virtualguard/projects/independent/website-build/subsites/blog (PRIVATE)

dependencies:
@algolia/client-search 5.24.0                  hexo-fs 5.0.0                                  hexo-theme-shokax 0.4.25
@common.js/p-limit 6.1.0                       hexo-generator-archive 2.0.0                   hexo-util 3.3.0
@reimujs/hexo-algoliasearch 0.1.0              hexo-generator-category 2.0.0                  instantsearch.js 4.78.2
@reimujs/hexo-renderer-markdown-it-plus 1.2.1  hexo-generator-index 4.0.0                     js-yaml 4.1.0
@waline/client 3.5.6                           hexo-generator-tag 2.0.0                       katex 0.16.22
algoliasearch 5.21.0                           hexo-pagination 4.0.0                          mouse-firework 0.1.1
dompurify 3.2.5                                hexo-renderer-ejs 2.0.0                        quicklink 2.3.0
es-toolkit 1.36.0                              hexo-renderer-markdown-it-plus 1.0.6           theme-shokax-anime 0.0.8
esbuild 0.25.3                                 hexo-renderer-pug 3.0.0                        theme-shokax-pjax 0.0.3
hexo 7.3.0                                     hexo-renderer-stylus 3.0.1                     twikoo 1.6.42
hexo-algoliasearch 2.0.1                       hexo-server 3.0.0                              unlazy 0.12.4
hexo-deployer-git 4.0.0                        hexo-theme-landscape 1.1.0
hexo-feed 1.1.2                                hexo-theme-reimu 1.8.2
```

### 你的网站的 `_config.yml` (可选)

```yaml
评论区配置
giscus:
  enable: true
  repo: virtualguard101/virtualguard101.github.io
  repoId: --
  category: Announcements
  categoryId: --
  mapping: mapping
  strict: 0
  reactionsEnabled: 1
  emitMetadata: 0
  inputPosition: bottom
  # commentTheme: light # this option is invalid, because the theme is set by the theme itself
  lang: zh-CN
```

### 你的网站的 `_config.reimu.yml` (可选)

```yaml
存在评论区配置模块，内容与_config.yml相同
```
