### ISSUE TITLE
twikoo 架設問題

### ISSUE THREAD

**Issue by speechless42** [D-Sketon/hexo-theme-reimu#104]
### 问题描述

當我架設 twikoo 便嘗試連接時，都沒有辦法連接到，沒有輸入框出現給我填寫。

### 复现步骤

當我設定 twikoo vercel 的評論時。不管我用您的 template 設定 _config.reimu.yml 還是我 clone 設定 內部的_config.yml。
設定值如下：

```
comment:
  # comment system title
  title:
    en: Leave a comment
    zh-CN: 说些什么吧！
    zh-TW: 說些什麼吧！
    ja: コメントを残す
  default: waline # default comment system, when you enable multiple comment systems

# 略

twikoo:
  enable: true
  envId: https://xxx.vercel.app  #容我先把名稱換成xxx
  region:
```
但是
hexo cl & hexo g & hexo s
後我第一篇文章會如下：

1.沒有輸入區域
![Image](https://github.com/user-attachments/assets/57868b2e-3f46-40b7-bfb8-fe0cbfd1e4db)

2.抓取不到
![Image](https://github.com/user-attachments/assets/f14baefc-9bb4-4663-9522-29810c8e7d11)

3.抓取不到
![Image](https://github.com/user-attachments/assets/83d821aa-bad3-4568-bf11-3242878fd3cd)

4.已確認伺服器狀態正常
![Image](https://github.com/user-attachments/assets/b22f2e78-f8af-47df-840e-c37ab7f24edf)

### 你的 Hexo 和 插件版本

```text
hexo-site@0.0.0 D:\personal\blog
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@4.0.0
├── hexo-generator-tag@2.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@7.0.1
├── hexo-renderer-stylus@3.0.1
├── hexo-server@3.0.0
├── hexo-theme-landscape@1.1.0
└── hexo@7.3.0
```

### 你的网站的 `_config.yml` (可选)

```yaml

```

### 你的网站的 `_config.reimu.yml` (可选)

```yaml

```
