### ISSUE TITLE
为什么不使用 npm install hexo-generator-search --save 实现搜索功能

### ISSUE THREAD

**Issue by jefferyjob** [D-Sketon/hexo-theme-reimu#2]

**Comment by jefferyjob** [comment]
怎么关闭了

**Comment by D-Sketon** [comment]
#14 已添加

**Comment by MliKiowa** [comment]
> 怎么关闭了

关掉原来的搜索
执行
`npm install hexo-generator-search --save`
在config.yml添加
```
search:
  path: search.json
  field: post
  content: true
generator_search:
  enable: true
```
