### ISSUE TITLE
关于使用giscus

### ISSUE THREAD

**Issue by sxf51** [D-Sketon/hexo-theme-reimu#22]
很漂亮的主题！大佬太强了！

_已解决，吧？_由于并不了解前端的东西，就用了一些笨方法。

- giscus盒子宽度问题：在css/style 中重新设置宽度，覆盖掉引用的default.css 

``` CSS
.giscus, .giscus-frame {
  width: auto;
}

.giscus-frame {
  width: 100%
}
```

- comments: false 失效问题(可能是我的Hexo 太老了)：在layout/_partial/after_footer.ejs 的 giscus.enable 判断中加一个逻辑

``` JS
<% if (theme.giscus.enable && page.comments) { %>
```
