### ISSUE TITLE
關於頁面缺失 <meta> 標籤 (og:image)

### ISSUE THREAD

**Issue by kayaoao** [D-Sketon/hexo-theme-reimu#54]
開發者您好，首先得致上謝意，讓不大懂程式的我，也能輕鬆擁有一個很可愛的網站。

我注意到某些頁面（比方說 `首頁/歸檔/關於我` 等）裡，不會產生 `<meta property="og:image">` 標籤，因此在「通訊或社群媒體」中分享時，縮圖預覽會是一片空白。

在網上爬了些文後發現一種解法，透過直接修改 `open_graph.ejs` 中的程式碼來解決：
```
let img_default = "https://example.com/images/banner.webp";
let images = options.image || options.images || page.photos || img_default || [];
```
想請教一下，這種方式除了更新 Hexo 後會被覆蓋，可能還有什麼弊端存在嗎？

**Comment by D-Sketon** [comment]
你好，首先感谢你使用我的主题
关于 `og:image`，我觉得我可以在主题中为 open_graph 添加 `default_og_image` 配置：
```yaml
open_graph:
  enable: true
  options:
    default_og_image: /images/banner.webp # https://d-sketon.github.io/images/banner.webp
```
这样无需修改Hexo源码，该特性会在主题下个版本添加，预计本周末发布
