### ISSUE TITLE
明暗更改按钮对 giscus 评论插件无法生效 | 和两个小问题

### ISSUE THREAD

**Issue by MakkiShizu** [D-Sketon/hexo-theme-reimu#64]
1. 明暗更改按钮的问题：我已在电脑谷歌和手机谷歌测试我自己的[网站](https://makkishizu.github.io/about/)，reimu自带的明暗更改按钮不会影响giscus这个评论的样式，下图是手机改变“暗色模式”得到的结果和电脑的情况
![4D74FDBC3EF91FF976C9D158D7E78FE3-compressed](https://github.com/user-attachments/assets/e8439e3b-54bf-4c4f-a234-dc043b851112)
![image](https://github.com/user-attachments/assets/5a30e67f-68a2-4bec-b161-5b8457b2c135)
以下是在`_config.reimu.yml`中的配置
```
giscus:
  enable: true
  repo: MakkiShizu/MakkiShizu.github.io
  repoId: --
  category: --
  categoryId: --
  mapping: mapping
  strict: 0
  reactionsEnabled: 1
  emitMetadata: 0
  inputPosition: bottom
  commentTheme: preferred_color_scheme
  lang: zh-CN
```

2. 是否有公开[hexo-theme-reimu效果展示](https://d-sketon.github.io/20240114/hexo-theme-reimu-content/)的原始代码实现？对于我（新手）来说 其中的一些效果比较难以找到，我想实现卡片效果时是看到[issue32](https://github.com/D-Sketon/hexo-theme-reimu/issues/32)并去[hexo-theme-reimu开发日志](https://d-sketon.github.io/)中才找到的。
3. 能否自定义代码块样式
```
辛苦作者了_(:з」∠)_
```
