### ISSUE TITLE
启用 mathjax 渲染时会被 KaTex 和 mathjax 同时渲染

### ISSUE THREAD

**Issue by syhanjin** [D-Sketon/hexo-theme-reimu#71]
nodejs 版本：18.18.2
主题版本: `1.1.0`
内层配置文件部分
```yaml
math:
  enable: true
  # if you want to use katex
  # It's better to use https://github.com/D-Sketon/hexo-renderer-markdown-it-plus for better performance
  # If you don't want to use it, please set `autoRender` to true to enable browser rendering
  katex:
    enable: false
    autoRender: false # whether to render the math in the browser, disabled by default
  # if you want to use mathjax
  # mathjax does not need any hexo plugins (no support for server rendering currently)
  mathjax:
    enable: true
    options: # see https://docs.mathjax.org/en/latest/web/configuration.html
      {
        tex:
          {
            tags: "ams",
            useLabelIds: true,
            inlineMath: [ [ "$", "$" ], [ '\\(', '\\)' ] ],
            displayMath: [ [ "$$", "$$" ], [ '\\[', '\\]' ] ],
            processEscapes: true,
            processEnvironments: true,
            autoload: { color: [ ], colorv2: [ "color" ] },
            packages: { "[+]": [ "noerrors" ] },
          },
        options:
          {
            skipHtmlTags:
              [ "script", "noscript", "style", "textarea", "pre", "code" ],
            ignoreHtmlClass: "tex2jax_ignore",
            processHtmlClass: "tex2jax_process",
          },
        loader: { load: [ "input/asciimath", "[tex]/noerrors" ] },
      }
```
初始 package.json
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server",
    "publish": "hexo publish draft */ --all"
  },
  "hexo": {
    "version": "7.3.0"
  },
  "dependencies": {
    "@reimujs/hexo-renderer-markdown-it-plus": "^1.0.0",
    "hexo": "^7.3.0",
    "hexo-deployer-git": "^4.0.0",
    "hexo-deployer-rsync": "^3.0.0",
    "hexo-filter-mermaid-diagrams": "^1.0.5",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^4.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-markdown-it-plus": "^1.0.6",
    "hexo-renderer-stylus": "^3.0.1",
    "hexo-theme-landscape": "^1.0.0",
    "hexo-theme-reimu": "^1.1.0"
  },
  "devDependencies": {
    "hexo-server": "^3.0.0"
  }
}
```
前端展示的公式被渲染了两遍（网页：<https://syhanjin.moe/20241128/5e114e805aee/>），鼠标放到公式上会提示 KaTex 的报错信息
尝试（均无效）
1. 将 `math.katex.autoRender` 设置为 `true`，无效后还原
2. 运行 `npm uninstall hexo-renderer-markdown-it-plus --save `
3. 运行 `npm uninstall @reimujs/hexo-renderer-markdown-it-plus --save`
4. 运行 `npm install hexo-renderer-marked`
5. 运行 `npm uninstall hexo-renderer-marked-katex --save `

尝试后 package.json
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server",
    "publish": "hexo publish draft */ --all"
  },
  "hexo": {
    "version": "7.3.0"
  },
  "dependencies": {
    "hexo": "^7.3.0",
    "hexo-deployer-git": "^4.0.0",
    "hexo-deployer-rsync": "^3.0.0",
    "hexo-filter-mermaid-diagrams": "^1.0.5",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^4.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.3.0",
    "hexo-renderer-stylus": "^3.0.1",
    "hexo-theme-landscape": "^1.0.0",
    "hexo-theme-reimu": "^1.1.0"
  },
  "devDependencies": {
    "hexo-server": "^3.0.0"
  }
}
```
