### ISSUE TITLE
请问作者能否帮忙给出“首页目录卡片”功能的具体实例？

### ISSUE THREAD

**Issue by R3c0ger** [D-Sketon/hexo-theme-reimu#74]
主要是在 _config.reimu.yml 中的配置方法，我一启用 home_categories 首页就报错

**Comment by D-Sketon** [comment]
可以把错误贴出来
例：
假设要要展示 计软杂谈/hexo 分类 和 计软杂谈 分类，使用默认封面
```yaml
home_categories:
  enable: true
  content:
    - categories: ["计软杂谈", 'hexo']
      cover:  
    - categories: "计软杂谈"
      cover:
```
