### ISSUE TITLE
是否考虑添加分享二维码

### ISSUE THREAD

**Issue by syhanjin** [D-Sketon/hexo-theme-reimu#77]
是否考虑在博客内添加分享按钮，生成文章二维码方便在朋友圈分享文章

**Comment by D-Sketon** [comment]
能否说的更加具体一些呢

**Comment by syhanjin** [comment]
生成包含文章概要的资料图片附上二维码地址，可以扫码查看文章？
类似于二维码分享
类似于，淘宝的分享之类的，因为要分享文章时只转发链接感觉怪怪的

**Comment by D-Sketon** [comment]
1.3.0 实验性地添加了该功能

**Comment by syhanjin** [comment]
QQ 分享和微信分享的图标没显示出来

**Comment by syhanjin** [comment]
_config.reimu.yml
share 部分
```yml
share:
  #  - facebook
  #  - twitter
  #  - linkedin
  #  - reddit
  - weibo
  - qq
  - weixin
```
完整
```yaml
########################################
# Basic Configuration
########################################

# main menu navigation
# for more icon information, please visit https://github.com/D-Sketon/hexo-theme-reimu/issues/30
menu:
  - name: home
    url: /
    icon: # default use taichi icon, you can use a hexadecimal representation of fontawesome or icon_font, like 'f0c1'
  - name: archives
    url: /archives
    icon:
  - name: about
    url: /about
    icon:
  - name: friend
    url: /friend
    icon:

banner: "/images/banner.webp" # which means themes/reimu/source/images/banner.webp
# You can also write it in the form of the following url
# banner: "https://example.com"

# If you want to use the srcset attribute, please enable it
banner_srcset:
  enable: false
  srcset:
    - src: "/images/banner-600w.webp"
      media: "(max-width: 479px)"
    - src: "/images/banner-800w.webp"
      media: "(max-width: 799px)"
    - src: "/images/banner.webp"
      media: "(min-width: 800px)"

favicon: "/images/favicon.ico" # which means themes/reimu/source/images/favicon.ico
# You can also write it in the form of the following url
# favicon: "https://example.com"

avatar: "avatar.jpg" # which means source/_data/avatar/avatar.jpg

# Open Graph
# see https://hexo.io/docs/helpers#open-graph
open_graph:
  enable: true
  options:
    #twitter_card: <twitter:card>
    #twitter_id: <twitter:creator>
    #twitter_site: <twitter:site>
    #twitter_image: <twitter:image>
    #google_plus: <g+:profile_link>
    #fb_admins: <fb:admin_id>
    #fb_app_id: <fb:app_id>
    default_og_image: /images/banner.webp # the default og:image for Open Graph, support absolute path

# Content
excerpt_link: Read More

# RSS
# need https://github.com/hexojs/hexo-generator-feed
rss: atom.xml

# Footer copyright
copyright:
# Need help choosing? Please see...
# https://creativecommons.org/choose/
# https://choosealicense.com/
# You can use pug like below...
# copyright: |-
#   <div style="flex-direction:column;align-items: center;"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>
#   All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></div>

footer:
  since: 2024 # 2024-current year
  powered: true
  count: true # show word count and reading time
  busuanzi: true
  icon:
    url: "../images/taichi.png" # this path is relative to the css/style.css, so it needs to go up one level to reach the images folder
    rotate: true
    mask: true # whether to use the images as a mask

# Sidebar
sidebar: left

social:
  # email: mailto:xxx@gmail.com
  github: https://github.com/syhanjin
  # google: https://plus.google.com/yourname
  # twitter: https://twitter.com/yourname
  # facebook: https://www.facebook.com/yourname
  # instagram: https://www.instagram.com/yourname
  # linkedin: https://www.linkedin.com/in/yourname
  # pinterest: https://www.pinterest.com/yourname
  # youtube: https://www.youtube.com/channel/yourname
  # vimeo: https://vimeo.com/yourname
  # flickr: https://www.flickr.com/photos/yourname
  # dribbble: https://dribbble.com/yourname
  # behance: https://www.behance.net/yourname
  bilibili: https://space.bilibili.com/547237569
  # weibo: https://weibo.com/yourname
  # zhihu: https://www.zhihu.com/people/yourname
  # reddit: https://www.reddit.com/user/yourname
  # tumblr: https://yourname.tumblr.com
  # medium: https://medium.com/@yourname
  # deviantart: https://yourname.deviantart.com
  # stackoverflow: https://stackoverflow.com/users/yourname
  # keybase: https://keybase.io/yourname
  # telegram: https://t.me/yourname
  # discord: https://discordapp.com/users/yourname
  # steam: https://steamcommunity.com/id/yourname

share:
  #  - facebook
  #  - twitter
  #  - linkedin
  #  - reddit
  - weibo
  - qq
  - weixin

widgets:
  - category
  #  - tag
  - tagcloud
# - archive
# - recent_posts

# Widget behavior
archive_type: "monthly"
show_count: false
recent_posts_limits: 5

########################################
# CSS
########################################

anchor_icon: # default use '#' icon, you can use a hexadecimal representation of fontawesome or icon_font, like 'f0c1'

reimu_cursor: true

# set to false to enable fontawesome
icon_font: 4552607_tq6stt6tcg

# https://fonts.google.com/
font:
  article:
    - Mulish
    - Noto Serif SC
  code:
    # - Ubuntu Mono
    # - Source Code Pro
    - JetBrains Mono

dark_mode:
  enable: true # set to true to make your website default to dark mode

########################################
# Markdown Display
########################################

math:
  enable: true
  # if you want to use katex
  # It's better to use https://github.com/D-Sketon/hexo-renderer-markdown-it-plus for better performance
  # If you don't want to use it, please set `autoRender` to true to enable browser rendering
  katex:
    enable: false
    autoRender: false # whether to render the math in the browser, disabled by default
  # if you want to use mathjax
  # mathjax does not need any hexo plugins (no support for server rendering currently)
  mathjax:
    enable: true
    options: # see https://docs.mathjax.org/en/latest/web/configuration.html
      {
        tex:
          {
            tags: "ams",
            useLabelIds: true,
            inlineMath: [ [ "$", "$" ], [ '\\(', '\\)' ] ],
            displayMath: [ [ "$$", "$$" ], [ '\\[', '\\]' ] ],
            processEscapes: true,
            processEnvironments: true,
            autoload: { color: [ ], colorv2: [ "color" ] },
            packages: { "[+]": [ "noerrors" ] },
          },
        options:
          {
            skipHtmlTags:
              [ "script", "noscript", "style", "textarea", "pre", "code" ],
            ignoreHtmlClass: "tex2jax_ignore",
            processHtmlClass: "tex2jax_process",
          },
        loader: { load: [ "input/asciimath", "[tex]/noerrors" ] },
      }

# mermaid url https://github.com/knsv/mermaid
# need https://github.com/webappdevelp/hexo-filter-mermaid-diagrams
mermaid:
  enable: true

code_block:
  expand: 30 # true | false | number

########################################
# Analytics
########################################

baidu_analytics: false
google_analytics: G-xxxxxxxxxx
clarity: false

########################################
# Comment system
########################################

# valine comment system. https://valine.js.org
# version 1.5.1
# notify and verify have been deprecated
valine:
  enable: false # if you want to use valine,please set this value is true
  appId: # leancloud application app id
  appKey: # leancloud application app key
  pageSize: 10 # comment list page size
  avatar: mp # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
  recordIP: true # whether to record the IP address of the commenters
  highlight: true # whether to highlight the code blocks
  visitor: false # whether to display the number of visitors

# https://waline.js.org/
# version 2.15.8
waline:
  enable: false
  serverURL:
  lang: zh-CN
  locale: { } # https://waline.js.org/guide/features/i18n.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80
  emoji:
    - https://unpkg.com/@waline/emojis@1.2.0/weibo
    - https://unpkg.com/@waline/emojis@1.2.0/alus
    - https://unpkg.com/@waline/emojis@1.2.0/bilibili
    - https://unpkg.com/@waline/emojis@1.2.0/qq
    - https://unpkg.com/@waline/emojis@1.2.0/tieba
    - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
  meta:
    - nick
    - mail
    - link
  requiredMeta:
    - nick
    - mail
  wordLimit: 0
  pageSize: 10
  pageview: true

# https://twikoo.js.org
twikoo:
  enable: false
  envId: # 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
  region:

# https://github.com/gitalk/gitalk/blob/master/readme-cn.md
gitalk:
  enable: false
  clientID:
  clientSecret:
  repo:
  owner:
  admin:
  md5: false

# https://giscus.app/zh-CN
giscus:
  enable: false
  repo:
  repoId:
  category:
  categoryId:
  mapping: mapping
  strict: 0
  reactionsEnabled: 1
  emitMetadata: 0
  inputPosition: bottom
  # commentTheme: light # this option is invalid, because the theme is set by the theme itself
  lang: zh-CN

########################################
# Search
########################################

# need https://github.com/LouisBarranqueiro/hexo-algoliasearch
# please add the following config in your _config.yml
# algolia:
#   appId: 'your applicationID'
#   apiKey: 'your apiKey'
#   adminApiKey: 'your adminApiKey'
#   indexName: 'your indexName'
#   chunkSize: 5000
#   fields:
#     - content:strip:truncate,0,500
#     - excerpt:strip
#     - gallery
#     - permalink
#     - photos
#     - slug
#     - tags
#     - title
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: "搜索....."
    hits_empty: "未发现与 「${query}」相关内容"
    hits_stats: "找到${hits}条结果（用时 ${time} ms）"

# need https://github.com/wzpan/hexo-generator-search
# please add the following config in your _config.yml
# search:
#   path: search.json # The filename must be search.json
#   field: post
#   content: true
generator_search:
  enable: false

########################################
# Animation
########################################

# Loader animation
preloader:
  enable: true
  text: 少女祈祷中...
  icon: # default use inline svg for fast speed, you can use a image url, like '/images/taichi.png'

# see https://github.com/D-Sketon/aos.js
animation:
  enable: true
  options:
    header:
      title: slide-up
      subTitle: slide-down
    home:
      post: fade-up
      widget: fade-up
      sidebar: fade-up
    article:
      whole: fade-up
      date: zoom-in
      category: zoom-in
      tag: zoom-in
      comment: zoom-in
      reading: zoom-in
      nav: fade-up
    archive:
      whole: fade-up
      tag: zoom-in
      category: zoom-in
      section: fade-up
      nav: fade-up

# see https://github.com/D-Sketon/mouse-firework
firework:
  enable: true
  options:
    excludeElements: [ "a", "button" ]
    particles:
      - shape: circle
        move: [ "emit" ]
        easing: easeOutExpo
        colors: [ "#ff5252", "#ff7c7c", "#ffafaf", "#ffd0d0" ]
        number: 20
        duration: [ 1200, 1800 ]
        shapeOptions:
          radius: [ 16, 32 ]
          alpha: [ 0.3, 0.5 ]
      - shape: circle
        move: [ "diffuse" ]
        easing: easeOutExpo
        colors: [ "#ff0000" ]
        number: 1
        duration: [ 1200, 1800 ]
        shapeOptions:
          radius: 20
          alpha: [ 0.2, 0.5 ]
          lineWidth: 6

########################################
# Extended features
########################################

# Clipboard configuration
clipboard:
  success: 复制成功(*^▽^*)
  fail: 复制失败 (ﾟ⊿ﾟ)ﾂ
  copyright: # whether to add a copyright for the clipped content
    enable: false
    count: 50 # The number of characters when the copyright is displayed
    content: 本文版权：本博客所有文章除特别声明外，均采用 BY-NC-SA 许可协议。转载请注明出处！

# show categories card on home page
home_categories:
  enable: true
  content:
    - categories: 嵌入式开发 # string (single-layer category) or array (multi-layer category)
      cover: # empty means random cover
    - categories: 线性代数
      cover:

# whether to display the notification when the article is outdated
outdate:
  enable: false
  daysAgo: 180 # The number of days after which the article is considered outdated
  message: 本文最后更新于 {time}，请注意文中内容可能已经发生变化。

# Sponsor
sponsor:
  enable: false
  tip: 请作者喝杯咖啡吧！
  icon:
    url: "../images/taichi.png" # this path is relative to the css/style.css, so it needs to go up one level to reach the images folder
    rotate: true
    mask: true # whether to use the images as a mask
  qr:
  # - name: 支付宝
  #   src: "/sponsor/alipay.jpg"
  # - name: 微信
  #   src: "/sponsor/wechat.png"

# ICP 备案
icp:
  icpnumber: # ICP备案号
  beian: # 网安备案号
  recordcode: # 网安备案链接中的recordcode参数

# show the copyright below each article
article_copyright:
  enable: true
  content:
    author: true
    link: true
    title: false
    date: false
    updated: true
    license: true

# Back To Top
top:
  enable: true
  icon:
    url: "../images/taichi.png" # this path is relative to the css/style.css, so it needs to go up one level to reach the images folder
    rotate: true
    mask: true # whether to use the images as a mask

########################################
# Experimental features
########################################

# Experimental, may have a lot of bugs, open with caution!
pjax:
  enable: false

# Experimental
# https://github.com/GoogleChromeLabs/quicklink
quicklink:
  enable: false
  # The `requestIdleCallback` timeout, in milliseconds.
  timeout: 3000
  # Whether or not the URLs within the options.el container should be treated as high priority.
  # When true, quicklink will attempt to use the fetch() API if supported (rather than link[rel=prefetch]).
  priority: true
  # Determine if a URL should be prefetched.
  # Only support string
  ignores: [ ]

# https://github.com/CodeByZach/pace
pace:
  enable: true

# Experimental
service_worker:
  enable: false

# Experimental
live2d:
  enable: false

########################################
# Vendor
########################################

# Dependent cdn links
# If you change the version of a js library, be sure to modify the corresponding integrity value
#vendor:
#  cdn_jsdelivr_gh: https://cdn.jsdelivr.net/gh/
#  cdn_jsdelivr_npm: https://cdn.jsdelivr.net/npm/
#  fastly_jsdelivr_gh: https://fastly.jsdelivr.net/gh/
#  fastly_jsdelivr_npm: https://fastly.jsdelivr.net/npm/
#  unpkg: https://unpkg.com/
#  webcache: https://npm.webcache.cn/
#  js:
#    clipboard:
#      src: webcache|clipboard@2.0.11/dist/clipboard.min.js
#      integrity: sha384-J08i8An/QeARD9ExYpvphB8BsyOj3Gh2TSh1aLINKO3L0cMSH2dN3E22zFoXEi0Q
#    lazysizes:
#      src: webcache|lazysizes@5.3.2/lazysizes.min.js
#      integrity: sha384-3gT/vsepWkfz/ff7PpWNUeMzeWoH3cDhm/A8jM7ouoAK0/fP/9bcHHR5kHq2nf+e
#    photoswipe:
#      src: webcache|photoswipe@5.4.4/dist/photoswipe.esm.min.js
#      integrity: sha384-WkkO3GCmgkC3VQWpaV8DqhKJqpzpF9JoByxDmnV8+oTJ7m3DfYEWX1fu1scuS4+s
#    photoswipe_lightbox:
#      src: webcache|photoswipe@5.4.4/dist/photoswipe-lightbox.esm.min.js
#      integrity: sha384-DiL6M/gG+wmTxmCRZyD1zee6lIhawn5TGvED0FOh7fXcN9B0aZ9dexSF/N6lrZi/
#    valine:
#      src: webcache|valine@1.5.1/dist/Valine.min.js
#      integrity: sha384-3ma91AExDeMAZ1rjTjaP8V2A2obQE+s5ltKRwYlwdpArz9xVbp0tF3b0VV2ACNPn
#    waline:
#      src: webcache|@waline/client@2.15.8/dist/waline.mjs
#      integrity: sha384-9sbqJjrfGjbkI6/PI4nU/MvBfEmkkPC4YK9I4zBeMIf1CVCZdCMH/KinBEAZII/5
#    twikoo:
#      src: webcache|twikoo@1.6.16/dist/twikoo.all.min.js
#      integrity: sha384-lDHsr5aZmkMS0eKnsUu6e9RWP+dRmn7sgjRAKGOAoXfMyzbUK6Qi86zZK7R+KvRV
#    gitalk:
#      src: webcache|gitalk@1.8.0/dist/gitalk.min.js
#      integrity: sha384-kspnZUWBoSWwoJHa0hBCXYbHGbhvU/lcEH5O8eVbSDhbPwsiVUTp/aGX/z/5EuMA
#    busuanzi:
#      src: webcache|busuanzi@2.3.0/bsz.pure.mini.js
#      integrity: sha384-0M75wtSkhjIInv4coYlaJU83+OypaRCIq2SukQVQX04eGTCBXJDuWAbJet56id+S
#    algolia:
#      src: webcache|algoliasearch@4.17.1/dist/algoliasearch-lite.umd.js
#      integrity: sha384-xvLS0jfKuoREs7pqkRI/OI8GcqohO5S+jQz7ZBtQXnsXmD+9jDOOY4cL6dCPzlrk
#    instantsearch:
#      src: webcache|instantsearch.js@4.56.1/dist/instantsearch.production.min.js
#      integrity: sha384-hHJCflT4KBLQyHfKO9vpstIcFKn/Y+KHTORelMMEn7mOp2AVPp+7fr03dLgZiV3J
#    pace:
#      src: webcache|pace-js@1.2.4/pace.min.js
#      integrity: sha384-k6YtvFUEIuEFBdrLKJ3YAUbBki333tj1CSUisai5Cswsg9wcLNaPzsTHDswp4Az8
#    mermaid:
#      src: webcache|mermaid@9.4.3/dist/mermaid.min.js
#      integrity: sha384-aG3Gai4tbCHF0iXo48HwLoOZyut7mBl50oMC9GD1m75xyHfJDv6w8hD/kZRD47aJ
#    firework:
#      src: webcache|mouse-firework@0.0.6/dist/index.umd.js
#      integrity: sha384-vkGvf25gm1C1PbcoD5dNfc137HzNL/hr1RKA5HniJOaawtvUmH5lTVFgFAruE9Ge
#    pjax:
#      src: webcache|theme-shokax-pjax@0.0.3/dist/index.umd.js
#      integrity: sha384-xneY1WY8hOfUzswrE4CrYq35N4BdVcxqxwHPr9zawE/jMSCxD+jAPU55x/jj3wlf
#    live2d:
#      base: fastly_jsdelivr_gh|D-Sketon/plugin-live2d/
#      js: fastly_jsdelivr_gh|D-Sketon/plugin-live2d/js/live2d-autoload.js
#    md5:
#      src: webcache|blueimp-md5@2.19.0/js/md5.min.js
#      integrity: sha384-JmVtRz6RWiXnA14QbIOJzPuU3MidULOpBP66deeLLyyoF4Tr/gZlbkHkL6vTthxH
#    quicklink:
#      src: webcache|quicklink@2.3.0/dist/quicklink.umd.js
#      integrity: sha384-aD7FsuQkS1ohgFKY41fJfeA+Wd/QRNnrOd9Bs58K3FzKdJJv8yPnYU8Tnp5z1agS
#    katex:
#      src: webcache|katex@0.16.11/dist/katex.min.js
#      integrity: sha384-7zkQWkzuo3B5mTepMUcHkMB5jZaolc2xDwL6VFqjFALcbeS9Ggm/Yr2r3Dy4lfFg
#    katex_auto_render:
#      src: webcache|katex@0.16.11/dist/contrib/auto-render.min.js
#      integrity: sha384-43gviWU0YVjaDtb/GhzOouOXtZMP/7XUzwPTstBeZFe/+rCMvRwr4yROQP43s0Xk
#    mathjax:
#      src: webcache|mathjax@3.2.2/es5/tex-mml-chtml.js
#      integrity: sha384-Wuix6BuhrWbjDBs24bXrjf4ZQ5aFeFWBuKkFekO2t8xFU0iNaLQfp2K6/1Nxveei
#  css:
#    photoswipe: webcache|photoswipe@5.4.4/dist/photoswipe.css
#    katex: webcache|katex@0.16.11/dist/katex.min.css
#    waline: webcache|@waline/client@2.15.8/dist/waline.css
#    gitalk: webcache|gitalk/dist/gitalk.css
#    fontawesome:
#      high_priority:
#        - webcache|@fortawesome/fontawesome-free@6.5.1/css/regular.min.css
#        - webcache|@fortawesome/fontawesome-free@6.5.1/css/solid.min.css
#      low_priority:
#        - webcache|@fortawesome/fontawesome-free@6.5.1/css/brands.min.css
#        - webcache|@fortawesome/fontawesome-free@6.5.1/css/v5-font-face.min.css
#        - webcache|@fortawesome/fontawesome-free@6.5.1/css/v4-font-face.min.css
#    aos: webcache|@reimujs/aos@0.1.0/dist/aos.css
```
样例 https://syhanjin.moe/20241214/4941f8fb48b8/
