### ISSUE TITLE
[bug]数学公式的下标无法正常显示

### ISSUE THREAD

**Issue by R3c0ger** [D-Sketon/hexo-theme-reimu#78]
无论行间还是行内公式，在某些情况下（暂时还没有总结出来，我大脑不够用了），用于下标的下划线会两两配对，先行解释成 Markdown 语法中的斜体样式，导致公式无法加载：

![图片](https://github.com/user-attachments/assets/415e32d8-1834-4e37-a991-ee06ee039542)

```markdown
---
title: test
date: 2024-12-28 12:08:54
---

$$
e^x=\lim_{n\to\infty} \left( 1+\frac{x}{n} \right)^n
$$

文本 $\int{a}_c = a{i}$ 文本

文本 $\int{a}_c = a_{i}$ 文本，崩了

文本 $\int{a} _c = a_{i}$ 文本，崩了

文本 $\int{a}_{c} = a_{i}$ 文本，崩了

文本 $\int{a} _{c} = a_{i}$ 文本，崩了

文本 $\int{a}_{c} = a_ {i}$ 文本，崩了

文本 $\int{a}_{c} = a_ i$ 文本，崩了


---

文本 $\int{a}_c = a_i$ 文本

文本 $\int{a}_c = a _i$ 文本

文本 $\int{a}_c = a _{i}$ 文本

文本 $\int{a} _c = a _{i}$ 文本

文本 $\int{a}_{c} = a _{i}$ 文本

文本 $\int{a} _{c} = a _{i}$ 文本

文本 $\int{a}_{c} = a _ {i}$ 文本

文本 $\int{a}_{c} = a _ i$ 文本

```

_config.reimu.yml 中的数学公式相关配置如下：

```yaml
math:
  enable: true
  katex:
    enable: false
    autoRender: false
  mathjax:
    enable: true
    options: 
      {
        tex:
          {
            tags: "ams",
            useLabelIds: true,
            inlineMath: [["$", "$"], ['\\(', '\\)']],
            displayMath: [["$$", "$$"], ['\\[', '\\]']],
            processEscapes: true,
            processEnvironments: true,
            autoload: { color: [], colorv2: ["color"] },
            packages: { "[+]": ["noerrors"] },
          },
        options:
          {
            skipHtmlTags:
              ["script", "noscript", "style", "textarea", "pre", "code"],
            ignoreHtmlClass: "tex2jax_ignore",
            processHtmlClass: "tex2jax_process",
          },
        loader: { load: ["input/asciimath", "[tex]/noerrors"] },
      }
```
