### ISSUE TITLE
部分疑问与建议

### ISSUE THREAD

**Issue by qsy1225** [D-Sketon/hexo-theme-reimu#84]
### 建议描述

**您好，感谢您做出一个如此精美、功能强大的博客。我有些小问题和一些小建议。**
#### aplayer播放器相关：
```yml
aplayer:
    enable: true
    options:
    audio: [
        {
            name: '多幸运',
            artist: '韩安旭',
            url: '/mt/how-lucky.mp3',
            cover: '/mt/how-lucky.webp',
            lrc: '/mt/how-lucky.lrc'
        },]
     fixed:
     autoplay: false
     loop: 'none'
     order: 'list'
     preload: 'metadata'
     volume:
     mutex:
     listFolded:
```
这是我的代码。我在source文件夹单独一个文件夹mt里面放着音频、封面、歌词。我的播放器封面、音频正常，只是不显示歌词。

![如图](https://github.com/user-attachments/assets/fa064499-4e05-4db7-b13b-5fca8274fb6d)
如图。我看您的正常显示歌词，希望您能帮我看看问题出现在哪。

####  视频插入相关
网页插入视频，可以点击播放，有声音，但网页一片空白（包括播放时）。画中画有个小画面。
```HTML
<video 
    src="/video/banana.mp4" 
    controls 
    style="width: 100%; height: auto; max-width: 500px;">
</video>
```
此为md里面的代码。在我之前的博客里它是正常的。请[点击这里](https://qsy.wiki/2025/02/05/banana/)前往我的网站看看，我不知道问题出在哪里。

#### 关于多语言的询问。
我看主题source里面是有语言yml的。我尝试去实现一键切换语言和一键切换文章语言，可惜全失败了。
不知您打算怎么做。切换文章语言有插件 i18n generator，我希望您能尝试下。
主动切换那些主页、关于 等的文件有，但没有切换键。如果您嫌麻烦不想切换文章，只加个切换选项也可以。

#### 深色模式相关
希望能出个自动模式（auto）--自动识别其系统模式来决定用哪种。

#### Markdown相关
之前我用的主题是 三钻的Aurora。它里面有个自定义容器，如以下代码：
```
:::details sth
content
:::
```
它的效果是点击展开。还有warning、danger。
这是相关链接。[介绍](https://aurora.tridiamond.tech/cn/configs/markdown.html)，[效果](https://blog.bennyxguo.com/post/b695af22372019b5213d1466cd06b4ba)。
希望您考虑下能添加到您的博客里。

### 再次感谢您。
