### ISSUE TITLE
拉取不成功

### ISSUE THREAD

**Issue by magicboy0409** [D-Sketon/hexo-theme-reimu#90]
### 问题描述

我使用 npm update 更新主題，然後在 node_modules 中，我所需要的如 Aplayer 或是 i18n 之類的內容都有，包含我查看了 layout>_partial>header.ejs 中的內容，只有 node_modules 中的有 i18n 的功能，我在 themes 中的沒有，並且我嘗試著 npm install ，同樣無效，往前查看了其他類似問題的人，多加了 @1 來更新，同樣無效，是否能夠在不影響我自己的設定的情況下將未更新完全的內容補齊？

### 复现步骤

1. 嘗試使用設置 i18n
2. 發現怎麼設置都不成功
3. 嘗試從本機上尋找設置 i18n 的代碼
4. 什麼都沒發現
5. 從這裡開始尋找
6. 找到了
7. 從 node_modules尋找，找到了，結果vs code的放大鏡似乎不會把 node_modules 的內容放進搜索結果之中。

### 你的 Hexo 和 插件版本

```text
C:\Users\KuroNeko\Desktop\hexo\blog>npm ls --depth0
hexo-site@0.0.0 C:\Users\KuroNeko\Desktop\hexo\blog
+-- hexo-deployer-git@4.0.0
+-- hexo-generator-archive@2.0.0
+-- hexo-generator-category@2.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-i18n@0.0.10
+-- hexo-generator-index@4.0.0
+-- hexo-generator-search@2.4.3
+-- hexo-generator-sitemap@3.0.1
+-- hexo-generator-tag@2.0.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-marked@6.3.0
+-- hexo-renderer-stylus@3.0.1
+-- hexo-server@3.0.0
+-- hexo-tag-embed@1.0.0
+-- hexo-theme-landscape@1.0.0
+-- hexo-theme-reimu@1.4.0
`-- hexo@7.3.0
```

### 你的网站的 `_config.yml` (可选)

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 書士的書桌
subtitle: '這裡是我的小書桌(其實是電腦)'
description: '我會分享一些有趣的事情或一些酷東東！'
keywords:
author: 摸書士
language: [zh-TW, en]
timezone: ''

# i18n
i18n:
  type: [page, post]
  generator: [archive, category, tag, index]

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.magicboy.xyz/
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-reimu

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: 
  branch: master

search:
  path: search.json # 文件名必須為search.json
  field: post
  content: true

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content: true
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: https://i.imgur.com/lTQv4cF.png
  autodiscovery: true
  template:

sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  rel: true
  tags: true
  categories: true

player:
  aplayer:
    enable: true
    options:
      audio: [] # audio list
      fixed:
      autoplay:
      loop:
      order:
      preload: 
      volume:
      mutex:
      listFolded:
      lrcType:
```

### 你的网站的 `_config.reimu.yml` (可选)

```yaml

```
